Custo eletronica
radar-pi/relatorios pull request #11
Opened 2019-03-31 20:45 UTC by kewinkiister

Foi feito a tabela de custos para eletrônica

2019-03-31 20:48 UTC, marimendes commented on editaveis/aspectosgerais.tex
> +<<<<<<< HEAD
Ta com um conflito aqui

2019-03-31 20:49 UTC, marimendes requested changes
Tem um conflito pra resolver

2019-03-31 20:51 UTC, kewinkiister commented on editaveis/aspectosgerais.tex
> +<<<<<<< HEAD
Corrigi e subi a nova versão já

2019-03-31 20:52 UTC, kewinkiister commented on editaveis/aspectosgerais.tex
> +<<<<<<< HEAD
O que tenho que fazer agora?

2019-03-31 20:57 UTC, marimendes commented on editaveis/aspectosgerais.tex
> +>>>>>>> 4ef4c5a9d179b0ced8d6ff52122a2aacd641c19d
Ficou faltando apagar isso aqui só.

2019-03-31 21:00 UTC, kewinkiister commented on editaveis/aspectosgerais.tex
> +>>>>>>> 4ef4c5a9d179b0ced8d6ff52122a2aacd641c19d
Tá vê agora de novo

2019-03-31 21:01 UTC, sconetto requested changes
Os arquivos `.DS_Store`, `rudix.py`, `tcc.bcf` e `tcc.run.xml` estão no PR e não deveriam ser incluídos no repositório.
Nesse PR tem também adições da branch de EAP e da branch de introdução, está correto?
Tem adição no README que não é necessária (adiciona um "a").
Na linha  59 do `aspectosgerais.tex` começa um comentário, não seria o caso de remover essa parte do texto? (o mesmo vale para o `elementosdopostexto.tex`)

2019-03-31 21:19 UTC, kewinkiister commented
Eu posso dar o comando (git rm meu_arquivo.txt) para excluir essas branchs que eu baixei?

2019-04-01 19:32 UTC, sconetto approved these changes

2019-04-01 19:36 UTC, marimendes approved these changes

2019-04-01 19:47 UTC, merged