Energia
radar-pi/relatorios pull request #8
Opened 2019-03-31 17:47 UTC by dannybemfica

.

2019-03-31 17:55 UTC, brendadias approved these changes
Restrições e Riscos Energia

2019-03-31 18:07 UTC, sconetto requested changes
Tem uma adição no `README.md` que acho que não é necessário, nos aspectos gerais onde tem o trabalho tem um conflito, está indicado pelo `<<<<<<HEAD`

e tem adição de um submódulo de energia que não tem nada, então não entendo o por que da adição.

2019-03-31 18:16 UTC, dannybemfica commented
> Tem uma adição no `README.md` que acho que não é necessário, nos aspectos gerais onde tem o trabalho tem um conflito, está indicado pelo `<<<<<<HEAD`
> 
> e tem adição de um submódulo de energia que não tem nada, então não entendo o por que da adição.

não tem nada ? qual o submodulo de restriçoes ou riscos? todos os submodulos acrescentados no meu latex tem algo escrito ...

2019-03-31 18:21 UTC, sconetto commented
![image](https://user-images.githubusercontent.com/11671985/55293077-7bf92180-53c8-11e9-9970-55786c007c83.png)
Se você for em arquivos modificados aqui no Pull Request tem esse submódulo vazio, não sei como foi adicionado e o que é mas está vazio e está aqui no pull request. enquanto as outras coisas acredito que ainda são relevantes.

2019-03-31 18:26 UTC, Diego-BF commented on editaveis/aspectosgerais.tex
> +\subsubsection{Riscos - Energia}
Sugiro mudar o nome dessa subseção para Energia apenas, para manter o padrão que tem sido seguido em outras partes do relatório.

2019-03-31 18:26 UTC, Diego-BF commented on editaveis/aspectosgerais.tex
> +   \item Locaização Geografica;
Faltou o l no meio de localização e acho q o geográfica é com letra minúscula nesse caso, não?

2019-03-31 18:27 UTC, dannybemfica commented on editaveis/aspectosgerais.tex
> +\subsubsection{Riscos - Energia}
ok

2019-03-31 18:29 UTC, dannybemfica commented
> ![image](https://user-images.githubusercontent.com/11671985/55293077-7bf92180-53c8-11e9-9970-55786c007c83.png)
> @dannybemfica Se você for em arquivos modificados aqui no Pull Request tem esse submódulo vazio, não sei como foi adicionado e o que é mas está vazio e está aqui no pull request. enquanto as outras coisas acredito que ainda são relevantes.

ok, acredito que houve um problema com a minha parte e a da brenda juntas, estou arrumando!, cancela essa pull e abre outra ?

2019-04-01 19:21 UTC, sconetto approved these changes

2019-04-01 19:25 UTC, merged